import dynamic from "next/dynamic";
import Head from "next/head";
import Link from "next/link";
import examples from "../examples.json";

// FIXME:
// @ts-ignore
const SimpleBar = dynamic(() => import("simplebar-react"), {
  ssr: false,
});

export default dynamic(() => Promise.resolve(Home), { ssr: false });

function Home() {
  if (typeof window === "undefined") return null;
  return (
    <div className='h-screen relative bg-black flex items-center justify-center'>
      <Head>
        <title>Hello Web3!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <video
          loop
          autoPlay
          muted
          src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
          className='w-full h-full object-cover'
        >
          Your browser does not support the video tag.
        </video>
        <SimpleBar className="absolute rounded-lg md:rounded-3xl w-9/12 h-4/5">
          <div className="absolute w-full h-full flex flex-col gap-4 p-4 overflow-auto rounded-lg shadow-sm  md:gap-8 md:p-8 md:shadow-inner md:rounded-3xl md:backdrop-opacity-30 md:backdrop-invert">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
                {examples.map(({ name, description, url, technologyStack }) => (
                  <div
                    key={name}
                    className="flex flex-col gap-2 md:gap-4 p-2 transition-all duration-200 ease-in-out bg-white md:border-white rounded-md md:bg-inherit md:p-4 hover:border
                  text-[#24292f] md:text-white border-gray-300 border md:border-0"
                  >
                    <div className="flex justify-between">
                      <Link className="text-2xl" href={url}>
                        {name}
                      </Link>

                      <Link
                        href={"https://github.com/luzhenqian/web3-examples"}
                        target="_blank"
                      >
                        <div className="flex items-center h-8 gap-2 px-2 border border-gray-300 rounded-md md:hidden">
                          <StartIcon />
                          <span>Start</span>
                        </div>
                      </Link>
                    </div>
                    <div className="text-sm text-[#57606a] md:text-inherit">
                      {description}
                    </div>
                    <div className="text-sm font-bold">技术栈</div>
                    <ul>
                      {technologyStack.map((tech) => (
                        <li key={tech}>{tech}</li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
          </div>
        </SimpleBar>
      </div>
  );
}

function StartIcon() {
  return (
    <svg
      aria-hidden="true"
      height="16"
      viewBox="0 0 16 16"
      version="1.1"
      width="16"
      data-view-component="true"
    >
      <path
        fillRule="evenodd"
        d="M8 .25a.75.75 0 01.673.418l1.882 3.815 4.21.612a.75.75 0 01.416 1.279l-3.046 2.97.719 4.192a.75.75 0 01-1.088.791L8 12.347l-3.766 1.98a.75.75 0 01-1.088-.79l.72-4.194L.818 6.374a.75.75 0 01.416-1.28l4.21-.611L7.327.668A.75.75 0 018 .25zm0 2.445L6.615 5.5a.75.75 0 01-.564.41l-3.097.45 2.24 2.184a.75.75 0 01.216.664l-.528 3.084 2.769-1.456a.75.75 0 01.698 0l2.77 1.456-.53-3.084a.75.75 0 01.216-.664l2.24-2.183-3.096-.45a.75.75 0 01-.564-.41L8 2.694v.001z"
      ></path>
    </svg>
  );
}


